language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  - POSTGRES_PASSWORD=postgres

services:
  - postgresql

before_install:
  - chmod +x mvnw

before_script:
  - psql -c "CREATE DATABASE planner --locale=uk_UA.UTF-8;" -U postgres
  - psql -c "CREATE USER planner WITH PASSWORD 'postgres';" -U postgres
